language: go

sudo: required
dist: xenial

env:
  - GO111MODULE=on

go:
  - 1.x
  - master
  - tip

matrix:
  fast_finish: true
  allow_failures:
    - go: master
    - go: tip

install:
  - go get github.com/mattn/goveralls@master

script:
  - goveralls -v -race -covermode=atomic -service=travis-ci

#deploy:
#  on:
#    condition: $TRAVIS_GO_VERSION =~ ^1\.8\.[0-9]+$
